package example

import "github.com/stretchr/testify/mock"

import context "golang.org/x/net/context"

// MockGreeterServer is an autogenerated mock type for the GreeterServer type
type MockGreeterServer struct {
	mock.Mock
}

// Greet provides a mock function with given fields: _a0, _a1
func (_m *MockGreeterServer) Greet(_a0 context.Context, _a1 *GreetRequest) (*GreetResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *GreetResponse
	if rf, ok := ret.Get(0).(func(context.Context, *GreetRequest) *GreetResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GreetResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *GreetRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
