package example

import "github.com/stretchr/testify/mock"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// MockGreeterClient is an autogenerated mock type for the GreeterClient type
type MockGreeterClient struct {
	mock.Mock
}

// Greet provides a mock function with given fields: ctx, in, opts
func (_m *MockGreeterClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	ret := _m.Called(ctx, in, opts)

	var r0 *GreetResponse
	if rf, ok := ret.Get(0).(func(context.Context, *GreetRequest, ...grpc.CallOption) *GreetResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GreetResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *GreetRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
