package influxtest

import (
	"context"

	"github.com/nullstyle/go/influx"
	"github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// HandleAction provides a mock function with given fields: ctx, action
func (_m *Handler) HandleAction(ctx context.Context, action influx.Action) error {
	ret := _m.Called(ctx, action)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, influx.Action) error); ok {
		r0 = rf(ctx, action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
