package mocks

import "github.com/stretchr/testify/mock"

// Backend is an autogenerated mock type for the Backend type
type Backend struct {
	mock.Mock
}

// Getenv provides a mock function with given fields: _a0
func (_m *Backend) Getenv(_a0 string) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Getwd provides a mock function with given fields:
func (_m *Backend) Getwd() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LookupPath provides a mock function with given fields: program
func (_m *Backend) LookupPath(program string) (string, error) {
	ret := _m.Called(program)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(program)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(program)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
