package value

type Parser Peg {
  Result V
}

first <- sp magnitude sp unit !.
unit <- < .* > { 
  p.Result.U = buffer[begin:end]
}
magnitude <- < sci / float_exp /  float / int_exp / int > {
  p.Result.M = buffer[begin:end]
}

sci <- float 'E' int
float_exp <- float '^' exp
float <-  minus? (zero / not_zero) '.' [0-9]+
int_exp <- int '^' exp
int <-  zero / (minus? not_zero)


exp <- minus? not_zero
zero <- '0'
not_zero <- [1-9][0-9]*
minus <- '-'
sp <- ( ' ' / '\t' )*